name: stopper
description: A bottom sheet that can be expanded to one of the pre-defined stop heights by dragging.
version: 1.0.2

homepage: https://github.com/JoDeveloper/flutter-stopper

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
